// <auto-generated />
namespace IAAI_TW_01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Feat_AddTables_Expert : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Feat_AddTables_Expert));
        
        string IMigrationMetadata.Id
        {
            get { return "202503241945082_Feat_AddTables_Expert"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
