// <auto-generated />
namespace IAAI_TW_01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class UpdateTables_SupervisorAndExpert_Hsitory_AllowHtml : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateTables_SupervisorAndExpert_Hsitory_AllowHtml));
        
        string IMigrationMetadata.Id
        {
            get { return "202504221600476_UpdateTables_SupervisorAndExpert_Hsitory_AllowHtml"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
