// <auto-generated />
namespace IAAI_TW_01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class UpdateTalbe_ExpertModifyFields_AddCoverNameAndCHangeDisplayName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateTalbe_ExpertModifyFields_AddCoverNameAndCHangeDisplayName));
        
        string IMigrationMetadata.Id
        {
            get { return "202504240741379_UpdateTalbe_ExpertModifyFields_AddCoverNameAndCHangeDisplayName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
